### ISSUE TITLE
reorder is not working

### ISSUE THREAD

**Issue by ffoysal** [donmstewart/porter-kustomize#3]
https://github.com/donmstewart/porter-kustomize/blob/27ac87d7a3d5ad33e3d7cb96ea0085c07137c9f4/pkg/kustomize/schema/kustomize.json#L16

**Comment by donmstewart** [comment]
Adding `--reorder` flag from kustomize v3.x to the mixin.

**Comment by donmstewart** [comment]
Could you confirm `porter-kustomize-v0.2-beta-3-0e19ca4` resolves your issue.

**Comment by donmstewart** [comment]
--reorder flag added.
